// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYIB1Pr74lTNCMHzqUvmHpJdfQI21E4Oo',
    appId: '1:217842651514:web:27f3745c0459782498c6c3',
    messagingSenderId: '217842651514',
    projectId: 'flashcook-poc',
    authDomain: 'flashcook-poc.firebaseapp.com',
    storageBucket: 'flashcook-poc.firebasestorage.app',
    measurementId: 'G-J79FPVNNJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEHbSmOEFOhb188MqbMSFPRs5rxH3we3k',
    appId: '1:217842651514:android:5a5fc9cdc7b4852e98c6c3',
    messagingSenderId: '217842651514',
    projectId: 'flashcook-poc',
    storageBucket: 'flashcook-poc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1xEjTyi8fe24NIbZeCN0HcHMK2MKLVag',
    appId: '1:217842651514:ios:88fc406ab7da73f698c6c3',
    messagingSenderId: '217842651514',
    projectId: 'flashcook-poc',
    storageBucket: 'flashcook-poc.firebasestorage.app',
    iosBundleId: 'com.example.flashcookPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1xEjTyi8fe24NIbZeCN0HcHMK2MKLVag',
    appId: '1:217842651514:ios:88fc406ab7da73f698c6c3',
    messagingSenderId: '217842651514',
    projectId: 'flashcook-poc',
    storageBucket: 'flashcook-poc.firebasestorage.app',
    iosBundleId: 'com.example.flashcookPoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYIB1Pr74lTNCMHzqUvmHpJdfQI21E4Oo',
    appId: '1:217842651514:web:2e5e80054146bb7c98c6c3',
    messagingSenderId: '217842651514',
    projectId: 'flashcook-poc',
    authDomain: 'flashcook-poc.firebaseapp.com',
    storageBucket: 'flashcook-poc.firebasestorage.app',
    measurementId: 'G-9N6N1FR3VP',
  );
}
